markdown: kramdown
encoding: UTF-8
safe: true
auto: true
syntax_highlighter: true
highlighter: rouge
lis: true
permalink: /:title.html

name: "穿卡芦苇/NODEWEE"
author: "穿卡芦苇"

navigations:
  - title: 首页
    eng_title: Home
    class: fa fa-home
    href: /
  - title: 标签
    eng_title: Tags
    class: fa fa-tags
    href: /tags.html
