markdown: kramdown
safe: true
auto: true

encoding: UTF-8
lis: true
permalink: /blog/:title.html

name: "本站碎碎念"
author: "NodeWee"
atom-baseurl: "https://nodewee.github.io/blog"
disqus: "nodewee"

navigations:
  - title: 首页
    eng_title: Home
    class: fa fa-home
    href: http://nodewee.github.io
  - title: 标签
    eng_title: Tags
    class: fa fa-tags
    href: https://nodewee.github.io/blog/tags.html
  - title: 存档
    eng_title: Archive
    class: fa fa-archive
    href: https://nodewee.github.io/blog/archive.html